import { defineType } from "sanity";
import { stringField, textField, urlField, stringArray, panelObject } from "./fields";

export const siteSettings = defineType({
  name: "siteSettings",
  title: "Site settings",
  type: "document",
  fields: [
    stringField("name", "Name"),
    stringField("brand", "Brand"),
    stringField("location", "Location"),
    stringField("email", "Email"),
    stringField("helloLabel", "Hello link label"),
    urlField("githubUrl", "GitHub URL"),
    urlField("linkedinUrl", "LinkedIn URL"),
    stringField("resumeUrl", "Résumé path"),
    stringField("introEyebrow", "Intro eyebrow"),
    stringField("introTitle", "Intro title"),
    stringField("introEmphasis", "Intro emphasis"),
    stringArray("introLines", "Intro lines"),
    stringField("apartmentLabel", "Apartment label"),
    stringField("apartmentNote", "Apartment note"),
    stringArray("asideLines", "Room aside lines"),
    stringField("idleCaption", "Idle caption"),
    stringField("catCaption", "Cat caption"),
    stringField("speakerLabel", "Speaker label"),
    stringField("signature", "Signature"),
    stringField("footerTagline", "Footer tagline"),
    stringField("panelEyebrow", "Panel eyebrow"),
    panelObject("profile", "Profile", [
      stringField("portrait", "Portrait path"),
      textField("aboutLead", "About lead"),
      stringArray("aboutParagraphs", "About paragraphs"),
      stringArray("languages", "Languages"),
      stringArray("recognition", "Recognition"),
    ]),
    panelObject("panels", "Panel content", [
      panelObject("books", "Books", [
        stringArray("spines", "Decorative book spines"),
        stringField("noteTitle", "Note title"),
        textField("noteBody", "Note body"),
      ]),
      panelObject("travel", "Travel", [
        stringField("tabsLabel", "Tabs accessibility label"),
        textField("footnote", "Footnote"),
      ]),
      panelObject("projects", "Projects", [stringField("linkLabel", "GitHub link label")]),
      panelObject("music", "Music", [
        stringField("choicesLabel", "Choices label"),
        stringField("creditsPrefix", "Credits prefix"),
        stringField("artistLabel", "Artist label"),
        urlField("artistUrl", "Artist URL"),
        stringField("licensePrefix", "License prefix"),
        stringField("licenseLabel", "License label"),
        urlField("licenseUrl", "License URL"),
      ]),
      panelObject("photos", "Photos", [
        stringField("image", "Photo path"),
        stringField("imageAlt", "Photo alt text"),
        stringField("caption", "Caption"),
        stringField("byline", "Byline"),
        stringField("noteTitle", "Note title"),
        textField("noteBody", "Note body"),
      ]),
      panelObject("education", "Education", [
        stringField("seal", "Seal"),
        stringField("institutionLabel", "Institution label"),
        stringField("school", "School"),
        stringField("degree", "Degree"),
        stringField("years", "Years"),
        stringField("storyTitle", "Story title"),
        stringArray("storyParagraphs", "Story paragraphs"),
        stringField("linkLabel", "Résumé link label"),
      ]),
    ]),
  ],
  preview: { prepare: () => ({ title: "Rex’s Internet Apartment" }) },
});
