name: Check

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm
      - run: npm ci --legacy-peer-deps
      - run: npm run check
        env:
          CI: "true"
  studio:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm
          cache-dependency-path: studio/package-lock.json
      - run: npm --prefix studio ci
      - run: npm run sanity:build
        env:
          SANITY_STUDIO_TELEMETRY_DISABLED: "1"
